name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup Python
    - name: Setup Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # 3. Install system dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++ python3-dev

    # 4. Configure CMake
    - name: Configure CMake
      run: cmake -S simulator -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug

    # 5. Build
    - name: Build
      run: cmake --build build

    # 6. Run tests
    - name: Run tests
      run: ctest --output-on-failure --test-dir build
