name: CMake CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
      # 1. Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3. Install vcpkg dependencies
      - name: Set up vcpkg
        run: |
          git clone --depth 1 https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          set VCPKG_ROOT=%CD%\vcpkg
          vcpkg install gtest nanobind:x64-windows

      # 4. Configure CMake
      - name: Configure CMake
        run: cmake -S simulator -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_TOOLCHAIN_FILE=%CD%\vcpkg\scripts\buildsystems\vcpkg.cmake

      # 5. Build project
      - name: Build project
        run: cmake --build build --config ${{ matrix.build-type }}

      # 6. Run tests
      - name: Run tests
        run: |
          cd build
          ctest -C ${{ matrix.build-type }} --output-on-failure

      # 7. Optional: Install Python bindings and run a simple test
      - name: Test Python bindings
        run: |
          python -m pip install --upgrade pip
          cd python
          python -c "import wafer_simulator; print('Python bindings import OK')"
