name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install CMake
      - name: Setup CMake
        uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.31.0'

      # Install vcpkg
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git ${{ github.workspace }}/vcpkg
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat

      # Install dependencies via vcpkg
      - name: Install vcpkg dependencies
        run: |
          ${{ github.workspace }}/vcpkg/vcpkg install gtest nanobind:x64-windows

      # Configure CMake
      - name: Configure CMake
        run: cmake -S simulator -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      # Build
      - name: Build
        run: cmake --build build --config Debug

      # Run tests
      - name: Run tests
        run: ctest --test-dir build --output-on-failure -C Debug
