name: Build and Test WaferAlignment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install vcpkg
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat

      # Step 4: Install dependencies using vcpkg
      - name: Install dependencies
        run: |
          ./vcpkg install nanobind

      # Step 5: Set up CMake
      - name: Set up CMake
        uses: lukka/get-cmake@v3
        with:
          cmake-version: '3.21.2'

      # Step 6: Configure the project
      - name: Configure project
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

      # Step 7: Build the project
      - name: Build project
        run: cmake --build build --config Debug

      # Step 8: Run tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
