name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: CI / build
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup Python 3.12
    - name: Setup Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # 3. Install Python dependencies from requirements.txt
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r python/requirements.txt

    # 4. Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++ python3-dev

    # 5. Configure CMake
    - name: Configure CMake
      run: cmake -S simulator -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug

    # 6. Build
    - name: Build
      run: cmake --build build

    # 7. Run C++ tests
    - name: Run C++ tests
      run: ctest --output-on-failure --test-dir build
